// Copyright (c) 2012 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file. See the AUTHORS file for names of contributors.

#include "leveldb/filter_policy.h"

#include "leveldb/slice.h"
#include "util/hash.h"

namespace leveldb {

namespace {
static uint32_t BloomHash(const Slice& key) {
  return Hash(key.data(), key.size(), 0xbc9f1d34);
}

class BloomFilterPolicy : public FilterPolicy {
 public:
  explicit BloomFilterPolicy(int bits_per_key) : bits_per_key_(bits_per_key) {
    // We intentionally round down to reduce probing cost a little bit
    // 我们故意 向下舍入 以稍微降低 探测成本
    // k_ 为 hash function 的组数
    k_ = static_cast<size_t>(bits_per_key * 0.69);  // 0.69 =~ ln(2)
    if (k_ < 1) k_ = 1;
    if (k_ > 30) k_ = 30;
  }

  const char* Name() const override { return "leveldb.BuiltinBloomFilter2"; }

  void CreateFilter(const Slice* keys, int n, std::string* dst) const override {
    // Compute bloom filter size (in both bits and bytes)
    // 计算 布隆过滤器 大小 (同时用 位和字节 表示)
    size_t bits = n * bits_per_key_;

    // For small n, we can see a very high false positive rate.  Fix it
    // by enforcing a minimum bloom filter length.
    // 对于小的 n, 我们可以看到 非常高 的 误报率.
    // 通过强制使用 最小布隆过滤器长度 来修复它.
    if (bits < 64) bits = 64;

    size_t bytes = (bits + 7) / 8;
    bits = bytes * 8;

    const size_t init_size = dst->size();
    dst->resize(init_size + bytes, 0);
    // 记录 过滤器中的 探针数
    // 先 resize, 再 push_back, 所以 探针数 记录在 布隆过滤器 数据后边
    dst->push_back(static_cast<char>(k_));  // Remember # of probes in filter
    // [] 的优先级高于 &
    char* array = &(*dst)[init_size];
    // 对于每一个 key
    // 计算 k 组 hash 值
    for (int i = 0; i < n; i++) {
      // Use double-hashing to generate a sequence of hash values.
      // See analysis in [Kirsch,Mitzenmacher 2006].
      // 使用 双散列 生成一系列散列值.
      // 参见 [Kirsch,Mitzenmacher 2006] 中的分析.
      uint32_t h = BloomHash(keys[i]);
      // 向右旋转 17 位
      const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits
      for (size_t j = 0; j < k_; j++) {
        // bitpos => 取余得到 h 对应的 bit 位置 (针对 整个 布隆过滤器 数据)
        const uint32_t bitpos = h % bits;
        array[bitpos / 8] |= (1 << (bitpos % 8));
        h += delta;
      }
    }
  }

  // 返回 true  => 不一定存在
  // 返回 false => 一定不存在
  bool KeyMayMatch(const Slice& key, const Slice& bloom_filter) const override {
    const size_t len = bloom_filter.size();
    if (len < 2) return false;

    const char* array = bloom_filter.data();
    const size_t bits = (len - 1) * 8;

    // Use the encoded k so that we can read filters generated by
    // bloom filters created using different parameters.
    // 使用编码的 k 以便我们可以读取使用 不同参数 创建的 布隆过滤器 生成的过滤器
    const size_t k = array[len - 1];
    if (k > 30) {
      // Reserved for potentially new encodings for short bloom filters.
      // Consider it a match.
      // 为 短布隆过滤器 的潜在新编码 保留.
      // 认为它是匹配的 ()
      return true;
    }

    // 与 创建 类似
    // 检查 应该置位的每一位是否置位, 一旦 发现未置位, 立即返回 false
    uint32_t h = BloomHash(key);
    const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits
    for (size_t j = 0; j < k; j++) {
      const uint32_t bitpos = h % bits;
      if ((array[bitpos / 8] & (1 << (bitpos % 8))) == 0) return false;
      h += delta;
    }
    return true;
  }

 private:
  size_t bits_per_key_;
  size_t k_;
};
}  // namespace

const FilterPolicy* NewBloomFilterPolicy(int bits_per_key) {
  return new BloomFilterPolicy(bits_per_key);
}

}  // namespace leveldb
